### ISSUE TITLE
Unable to get the integration to start

### ISSUE THREAD

**Issue by ipw781** [MrSuicideParrot/hassio-speedtest-addon#1]
Hey, love this idea to use the speedtest.net CLI for more accurate results, but having trouble getting the addin to start.  Log below, let me know if I'm missing anything.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun speedtest (no readiness notification)
s6-rc: info: service legacy-services successfully started
[12:52:06] INFO: Starting speed test
==============================================================================
You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:
	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy
==============================================================================
License acceptance recorded. Continuing.
==============================================================================
Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:
       http://www.speedtest.net/privacy
==============================================================================
License acceptance recorded. Continuing.
jq: error: syntax error, unexpected QQSTRING_START, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
Media","interface":{"internalIp":"<removed>","name":"eth0","macAddr":"<removed>","isVpn":false,"externalIp":"<removed>"},"server":{"id":11445,"host":"lon.host.speedtest.net","port":8080,"name":"Structured     
jq: 1 compile error
./run: line 33: *8/1000000: syntax error: operand expected (error token is "*8/1000000")
jq: error: syntax error, unexpected QQSTRING_START, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
Media","interface":{"internalIp":"<removed>","name":"eth0","macAddr":"<removed>","isVpn":false,"externalIp":"<removed>"},"server":{"id":11445,"host":"lon.host.speedtest.net","port":8080,"name":"Structured     
jq: 1 compile error
./run: line 34: *8/1000000: syntax error: operand expected (error token is "*8/1000000")
jq: error: syntax error, unexpected QQSTRING_START, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
Media","interface":{"internalIp":"<removed>","name":"eth0","macAddr":"<removed>","isVpn":false,"externalIp":"<removed>"},"server":{"id":11445,"host":"lon.host.speedtest.net","port":8080,"name":"Structured     
jq: 1 compile error
[12:52:25] INFO: --------- Speed test ended ---------
./run: line 38: down_load_speed: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by MrSuicideParrot** [comment]
Hi!
Thank you very much for opening issue, this project is recent so it's prone to errors.
I have been running this add-on in my home assistant for 6 months and haven't seen this error.
Could you tell me two things, in which architecture are you running home assistant? (amd64, aarch64 ....), and are you specifying a speedtest server id?

**Comment by ipw781** [comment]
No problem, I fully understand where this integration is in terms of its lifecycle!

I'm running on a RPi 4, so aarch64?

I have 11445 specified as the server ID.  According to https://gist.github.com/ofou/654efe67e173a6bff5c64ba26c09d058 and https://www.speedtest.net/speedtest-servers-static.php this should be a London server.

Let me know if there's anything else that would be helpful to know.

Cheers.

**Comment by MrSuicideParrot** [comment]
Ok ok, I will test this add-on on the same platform to test if everything is working as expected.
If I'm not able to reproduce the error, I'll create a debug version to have more information about what is happening.

**Comment by MrSuicideParrot** [comment]
I think this issue has been solved with the latest release. Could you check?

**Comment by ipw781** [comment]
Add-on updated and appears to be working well! Measures are far more accurate than the native integration. 

Thanks so much for the fast turnaround, much appreciated. I just need to write an automation to schedule start the add-on now 🙂
