### ISSUE TITLE
Add-on resets custom entity icon

### ISSUE THREAD

**Issue by digitalMedic** [MrSuicideParrot/hassio-speedtest-addon#15]
Prior to installing speedtest add-on, I defined custom icons for the entities in the integrated Speedtest.  After installing and running the add-on, the custom icons do not show up on the entities when displayed (reverts back to default speedometer icon).  The custom icons are still defined in the entity's settings.

**Comment by MrSuicideParrot** [comment]
Hi! When I was creating the script I didn't thought about the possibility of having a custom icon (https://github.com/MrSuicideParrot/hassio-speedtest-addon/blob/d9cadf1e376db03693fb8bcedbba71185e0e11a4/speedtest/rootfs/etc/services.d/speedtest/run#L31C10-L31C10). Most probably this is as simple as removing the `icon` attribute from the json. Unfortunately, I don't know when I'll be able to test this. If you want to explore this change and if it works, I'll gladly accept a pull request.

**Comment by MrSuicideParrot** [comment]
This issue was fixed in the latest release.
