### ISSUE TITLE
Add-On is Not Listed on Add-on Page

### ISSUE THREAD

**Issue by gyildirim03** [MrSuicideParrot/hassio-speedtest-addon#2]
I'm using Home Assistant OS as a virtual machine. Already installed speedtestdotnet integration. Disabled auto-polling.  (My speedtest integration menu is different from your readme, I guess it's about version.  There is no frequency menu.) 

![resim](https://user-images.githubusercontent.com/74541714/218487903-f97222cb-16aa-40d2-ad9d-c77e9806960f.png)
![resim](https://user-images.githubusercontent.com/74541714/218488103-af5a715c-10fc-42e1-bbe8-ba4147f1a3a2.png)

Then added repository URL;

![resim](https://user-images.githubusercontent.com/74541714/218488283-2bbf5c48-4bd8-41e0-80d0-038400c80b85.png)

But when I search the Add-on repository, speedtest-addon is not listed;

![resim](https://user-images.githubusercontent.com/74541714/218488503-14ad2a47-7710-4eb6-98e9-60a15a47fb50.png)

In the supervisor logs, I can see 1 new repository is added, here is supervisor logs;

`23-02-13 17:07:47 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/MrSuicideParrot/hassio-speedtest-addon repository
23-02-13 17:07:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 1 new - 0 remove
23-02-13 17:09:15 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-02-13 17:09:15 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/MrSuicideParrot/hassio-speedtest-addon repository
23-02-13 17:09:15 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-02-13 17:09:15 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-02-13 17:09:18 INFO (MainThread) [supervisor.store] Loading add-ons from store: 69 all - 0 new - 0 remove`

After "Check Updates" button on add-on repository, no luck.

Thanks for the project, I'm getting inaccurate results between speedtestdotnet integration results and official speedtest-cli results (on another machine), I hope this add-on will solve the issue.

**Comment by MrSuicideParrot** [comment]
Hi! Thank you very much for your issue.

I have updated  my home assistant instance and noticed that the speedtest integration changed its settings, I think the new menu that you posted here (disable the "Enable polling for updates") must be the new correct way to disable the integration to run. But I need to test. If it is, will update the README accordingly. 

In regard to the second problem, will test a clean install of home assistant and try to figure out what is happening. What version of home assistant are you running?

**Comment by gyildirim03** [comment]
Hi,
Yesterday my Home Assistant version was 2023.2.3 , today I updated to latest version. 

Currently my HA looks like this;

Home Assistant 2023.2.4 
Supervisor 2023.01.1 
Operating System 9.5 
Frontend 20230202.0 - latest 

After update I checked add-on page, now I can see home assistant add-on. 

![resim](https://user-images.githubusercontent.com/74541714/218708325-97876702-82c4-49a1-b951-461c6b508271.png)

I installed add-on, tried to start and this menu appears;

![resim](https://user-images.githubusercontent.com/74541714/218709138-47d25951-2ac9-4332-8578-67b2691d3ec4.png)

When I click "Edit Config" , page redirects to config page but this message appears.

![resim](https://user-images.githubusercontent.com/74541714/218709431-fa450185-39c7-4788-ae8e-18847df7bd42.png)

**Comment by gyildirim03** [comment]
Update:

After reboot & clearing browser cache,  configuration page is now available. I accepted EULA, created an automation to run every hour and now it works perfectly. Thank you.

There is a slightly UI difference between the integration and this add-on.  The integration results contains  download, upload, ping and test server information. 

Speedtest Integration Result;
![resim](https://user-images.githubusercontent.com/74541714/218721233-5edfb292-538b-4778-999e-33324ae5c55a.png)

Speedtest Add-On Result:
![resim](https://user-images.githubusercontent.com/74541714/218721868-b822c6f4-9a54-4637-aa33-ef4b3a7a1d9a.png)

The add-on result does not have attributes section.  I've also checked the add-on logs, logs does not contain test server info too. 

Here is the add-on logs;

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun speedtest (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:17:05] INFO: Starting speed test
==============================================================================
You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:
	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy
==============================================================================
License acceptance recorded. Continuing.
[14:17:25] INFO: --------- Speed test ended ---------
[14:17:25] INFO: Download measured: 80
[14:17:25] INFO: Upload: 7
[14:17:25] INFO: Ping: 14.936
[14:17:25] INFO: --------- ---------
null
[14:17:25] INFO: Speedtest Download updated
null
[14:17:25] INFO: Speedtest Upload updated
null
[14:17:25] INFO: Speedtest Ping updated
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

As you can see, there is about 20% difference between integration results vs add-on results. (65mbps vs 80mbps)
Also I was getting wrong results with the integration because sometimes it was using test servers located in a wrong country. I'm living in Turkey but integration was using servers in Bulgaria. With this add-on, now I can select my own ISP's test server ID, and I'm getting accurate results.

Add-on works like a charm, solved my inaccurate test results problem. 
Thank you.
