### ISSUE TITLE
not work after last update 

### ISSUE THREAD

**Issue by lex-us345** [MrSuicideParrot/hassio-speedtest-addon#20]
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:38Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T07:49:43Z","message":"Error: [0] Cannot open socket","level":"error"}
./run: line 58: null: unbound variable
./run: line 60: null: unbound variable

**Comment by MrSuicideParrot** [comment]
Hi! 
Is this the output of the addon in debug mode? If not, could you provide me the output in debug mode (can be activated in the configuration tab of the addon?
Additionally, could you tell me the architecture where you are running home-assistant?

**Comment by lex-us345** [comment]
### these URLs:

	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy

==============================================================================

License acceptance recorded. Continuing.

{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:08Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:09Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:10Z","message":"Error: [0] Cannot read from socket: ","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:11Z","message":"Error: [0] Timeout occurred in connect.","level":"error"}
{"type":"log","timestamp":"2024-04-30T20:00:11Z","message":"Server Selection - Failed to find a working test server. (NoServers)","level":"error"}
./run: line 58: *8/10000: syntax error: operand expected (error token is "*8/10000")
./run: line 60: *8/10000: syntax error: operand expected (error token is "*8/10000")
[23:00:12] INFO: --------- Speed test ended ---------
[23:00:12] INFO: Download measured: 
[23:00:12] INFO: Upload: 
[23:00:12] INFO: Ping: 
[23:00:12] INFO: Server name: 
[23:00:12] INFO: Server location: 
[23:00:12] INFO: Server id: 
[23:00:12] INFO: Server country: 
[23:00:12] INFO: --------- ---------
./run: line 28: 6: unbound variable
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun speedtest (no readiness notification)
s6-rc: info: service legacy-services successfully started
[23:04:49] INFO: Starting speed test
==============================================================================

You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:

	https://www.speedtest.net/about/eula
	https://www.speedtest.net/about/terms
	https://www.speedtest.net/about/privacy

==============================================================================

Core
2024.4.4
Supervisor
2024.04.4
Operating System
12.2

Speedtest 
Current version: 1.6.2

**Comment by MrSuicideParrot** [comment]
I have tested the plugin with the versions you indicated and I wasn't able to replicate the issue. 
Are you using a fixed speed test server? If yes, could you test with other server?
Where are you running home assistant? Vm? Raspberry?

**Comment by lex-us345** [comment]
Hi!
I don't fixed the server, before this it was fixed
Raspberry Pi 4

**Comment by lex-us345** [comment]
Hi! 
Uninstall-install-uninstall-install-... ) and work again!
Thank you!

**Comment by lex-us345** [comment]
Thank you!
