### ISSUE TITLE
Sensor becomes unavailable because it's not updated

### ISSUE THREAD

**Issue by Kaot93** [MrSuicideParrot/hassio-speedtest-addon#3]
The add-on works, but it doesn't update my upload and download sensor, because the speed doesn't change. 
I think it would help to add more digits, currently my download always reads 58 Mbit/s and my upload 10.

Any way to add more detail to the measurement? My ping gets updated.

**Comment by MrSuicideParrot** [comment]
The official speedtest integration gives two digits of resolution for download and upload measurements. I updated the script to output the measurements with the same level of detail.

**Comment by Kaot93** [comment]
Works like a charm, thank you very much!
